name: Check GCP WIF Auth
on:
  workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest
    environment: dev
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      # Configure Workload Identity Federation via a credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: format('projects/{0}/locations/global/workloadIdentityPools/terraform-identity-provider-pool/providers/github',${{ secrets.PROJECT_NUMBER }})
          service_account: ${{ secrets.GCP_TF_SA }}

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Now you can run gcloud commands authenticated as the impersonated service account.
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud storage ls